openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: miniature-parakeet
  url: http://83.212.100.226:3002/v1
security:
- {}
tags:
- description: not yet ready
  name: qwerty
paths:
  /qwerty:
    post:
      operationId: createqwerty
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/qwerty'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/qwerty'
          description: successful operation
      summary: Creates the data
      tags:
      - qwerty
      x-eov-operation-handler: controllers/QwertyController
  /qwerty/{qwertyId}:
    delete:
      operationId: deleteqwerty
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: qwertyId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - qwerty
      x-eov-operation-handler: controllers/QwertyController
    get:
      operationId: getqwerty
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: qwertyId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/qwerty'
          description: successful operation
      summary: Get the element
      tags:
      - qwerty
      x-eov-operation-handler: controllers/QwertyController
    put:
      operationId: updateqwerty
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: qwertyId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/qwerty'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/qwerty'
          description: successful operation
      summary: Updates the element
      tags:
      - qwerty
      x-eov-operation-handler: controllers/QwertyController
  /qwerty/getAll:
    get:
      operationId: getAllqwerty
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/qwerty'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - qwerty
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/QwertyController
components:
  schemas:
    qwerty:
      example:
        qTitle: qTitle
        _id: _id
      properties:
        _id:
          type: string
        qTitle:
          type: string
      required:
      - qTitle
      type: object
